### ISSUE TITLE
Add a last build date information at the bottom of documentation main page

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#1000]
The last build date information at the bottom of the web site [main page](http://qgis.org/en/site/index.html) is a good indicator to follow build errors. Given the recent fails of QGIS website build due to errors in translation, it can be nice to also show this information at the bottom of QGIS Doc [main page](http://www.qgis.org/en/docs/index.html). This will be of great help i think once doc is released.
@rduivenvoorde I'm assigning it to you, feel free to unassign if inappropriate. Thanks

**Comment by rduivenvoorde** [comment]
@DelazJ there is actually already one, but on the 'main page' of the actual documentation build directory:
http://docs.qgis.org/testing/en/docs/
and 
http://docs.qgis.org/2.8/en/docs/
the page you are pointing to is actually a left over from times that we had ONE build covering both site and docs.
FYI: the reason we only show it on one frontpage is because we rsync to the (sometimes slow disk) qgis-server from the qgis2 build server. And have that date in the main template would mean we sync ALL pages every time.
BUT if you think it is more appropriate to put it on some more pages, just add the path to this IF-statement:
https://github.com/qgis/QGIS-Documentation/blob/master/themes/qgis-theme/page.html#L46
for docs, and 
https://github.com/qgis/QGIS-Website/blob/master/themes/qgis-theme/page.html#L46
for website.
Or just let me know if you want it on certain pages, and I'll do it.

**Comment by DelazJ** [comment]
Oh great! Sorry, I should have better looked these pages. better keep the info at this place. It's more coherent! Thanks.
BTW, I notice that the last build  of testing would be April 15th and can't indeed find newer commits (not sure it's a local cache matter). Could it be?

**Comment by rduivenvoorde** [comment]
Ah, thanks for noting!

I checked, and it appaered there was a faulty build container... removed and rebuild: fixed
