### ISSUE TITLE
Restructure the PYQGIS Doc?

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#1096]
Could the TOC of the [PyQGIS doc ](http://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/index.html) be more concise, putting together features that can be?
I find it a bit overloaded and wonder if some sections couldn't be merged under same chapter.

**Comment by anitagraser** [comment]
Since this issue was opened in 2016 (around release 2.18 https://docs.qgis.org/2.18/en/docs/pyqgis_developer_cookbook/index.html) the cookbook [has been revised by @elpaso in 2020](https://blog.qgis.org/2020/04/19/pyqgis-cookbook-revision-2020/) but the doc is still long (https://docs.qgis.org/3.28/en/docs/pyqgis_developer_cookbook/index.html). 

To me, the different sections make sense. I propose to close this issue.

**Comment by DelazJ** [comment]
Done.
