### ISSUE TITLE
[FEATURE] Move feature now benefits from Advanced Digitizing

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1289]
Original commit: https://github.com/qgis/QGIS/commit/e2cacade1d61d33607354d3e456fd6739d6707ed by web-flow

[FEATURE] Move feature now benefits from Advanced Digitizing

**Comment by DelazJ** [comment]
@3nids, is that possible to set the initial point of the displacement using the x and y constraint? When I select the move feature(s) tool, only x and y are enabled and I can change their value and see the marker on the canvas but I can't see how this position could be used as origin of the translation (pressing Enter does nothing eg). Is that possible?

Likewise, when I enable the CAD after I placed the origin point of the displacement, it only proposes x and y, not d or a to place relatively. --> The CAD should be enabled before you enable the move feature tool to have access to its full features (bug?).

**Comment by 3nids** [comment]
Yep it is possible:
1. select the feature
2. active move feature tool
3. enable cad
4. lock x and y
5. click on the point
5. do the move

https://youtu.be/EXmdiDAUXZI

> Likewise, when I enable the CAD after I placed the origin point of the displacement, it only proposes x and y, not d or a to place relatively. --> The CAD should be enabled before you enable the move feature tool to have access to its full features (bug?).

I would not consider this as a bug. The CAD cannot be aware of a point placed without it being enabled. So it cannot propose distance and angle.

**Comment by DelazJ** [comment]
Thanks for your quick answer. Much appreciated.
> 5. click on the point

This is what I was missing yesterday. I was not necessarily clicking **on** the point. I was expecting that clicking anywhere in the canvas would make the blocked point become the origin of the translation. Is that foolish expectation? This seems to be what happens if I use the add feature tool: the click is caught at the blocked position, regardless where I precisely click in the canvas.
I think my "mistake" was also due to the fact that when hovering over the blocked point, no visual marker led me think that clicking would snap to it.
Btw, I really fail to understand what happens when I do not click on the blocked point (my maths lessons are far away now) but I'm not sure it's what common users will expect.
>I would not consider this as a bug. The CAD cannot be aware of a point placed without it being enabled. So it cannot propose distance and angle.

Fair enough; will just advise to enable the CAD before any point addition

**Comment by DelazJ** [comment]
> This seems to be what happens if I use the add feature tool: the click is caught at the blocked position, regardless where I precisely click in the canvas.

And this is what happens when I place the destination point of "Move feature(s)": no need to click on the point: just click in the canvas and it's ok.

**Comment by 3nids** [comment]
yep, sorry, you're right this is a bug, you should be able to click anywhere.
can you report an issue and assign to me?

**Comment by DelazJ** [comment]
done at https://issues.qgis.org/issues/19141. Thanks

**Comment by 3nids** [comment]
fixed, thanks!
