### ISSUE TITLE
[FEATURE] Native support for XYZ tile layers

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1397]
Original commit: https://github.com/qgis/QGIS/commit/c4181fa04d8be377eb34a4f54be9cf139e0aa558 by wonder-sk

Yes, that means OpenStreetMap tiles and various other sources!

No GUI so far...

**Comment by fasiha** [comment]
I was very surprised when the XYZ tile renderer showed my tiles with north and south hemispheres switched. After digging, I discovered that there are two variant tile formats, origin at top-left or bottom-left. The [2.18 documentation](https://www.qgis.org/en/site/forusers/visualchangelog218/index.html#data-providers) doesn’t mention the awesome work @alexbruy who fixed this issue for 2.18 at https://issues.qgis.org/issues/16586 — use `{-y}` instead of `{y}` and we are golden!

Consider adding this to the changelog or documentation?

**Comment by DelazJ** [comment]
@fasiha the changelog is created at the release of QGIS version and doesn't get update so it only list new features and some bug fixes at the release time. If you want newer information on an issue related to that release, options are: look into the bug tracker or diff the QGIS commits.

About the 2.18 documentation, afaics there is no mention of the XYZ option (yet?). If you know about it and want to share/help, please provide a text, even a raw one (odt, txt, doc, comment below... with an indication where to place it ) and we'll take care of formatting and include it. If you feel a PR is better, do it too...
Anyway, thanks for the reminder...

**Comment by havatv** [comment]
Should be fixed with #4800.
