### ISSUE TITLE
Consider moving the "Developers Guide" from the Website to the Documentation

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS-Documentation#1566]
Part of Get Involved/Development section in the website, make more sense in documentation. this includes:
- Developement guidelines
- Plugin developement
- Adding GRASS tools (is this still updated/valid?)

This way this topics could be expanded.

Since this is not only PyQGIS, we might have to create a new "chapter".

**Comment by luipir** [comment]
I agree, I was writing documentation about Auth system. Part is in the PyQGIS cookbook, and part is how to create C++ Auth plugin. Python part is in QGIS-Documentation, and c++ part should go in QGIS-Website where reside documentation how to create c++ generic plugin.

I strongly suggest to move all in QGIS-Documentation

**Comment by DelazJ** [comment]
@SrNetoChan 
> Part of Get Involved/Development section in the website, make more sense in documentation. this includes:
> * Developement guidelines

Given that we explain to users how to report a bug or ask for a feature, I think we should also show them in the website how to technically improve the project if they have coding skills. We should keep a page that summarizes how they can help on coding and link them to the new chapter in the documentation.
Any idea on where such a chapter would be placed? Maybe create a new document `Contribution Guidelines` mixing the current doc guidelines and the development guidelines?

> * Plugin developement

IMHO, we should keep this in the website (in the page I'm mentioning above). This is a first insight of what QGIS provides as tools. I find the Python section nice to have as is. Maybe the C++ part should be reviewed and be more descriptive of what can be done rather than showing (unfinished) steps to do things.

> Adding GRASS tools (is this still updated/valid?)

Yes please, let's move it. I have never understood why it was there and not in GRASS part of the doc.

@luipir if the documentation is especially Auth plugin oriented, why not make a new section for the C++ part (or both languages?) in http://docs.qgis.org/testing/en/docs/user_manual/auth_system/index.html. I'm not sure it has its place in the dev guidelines nor the current c++ part in the website.

**Comment by SrNetoChan** [comment]
There is already some work done by @dakcarto in his documentation repository:

https://learning-center.boundlessgeo.com/desktop/intermediate/kernel_density/index.html

**Comment by SrNetoChan** [comment]
@DelazJ I agree with you, we should keep some of it in the website, which is more visible, and point to the documentation for more details.

I would keep documentation guidelines apart from this one. We could call it "development guidelines" anyway I guess.

> @luipir if your documentation is specifically Auth plugin oriented, why not make a new section for the C++ part (or both languages?) in http://docs.qgis.org/testing/en/docs/user_manual/auth_system/index.html. I'm not sure it has its place in the dev guidelines nor the current c++ part in the website.

I think we should separate what is useful for the users, and what is only for developers, even if we cross link the documents.

**Comment by yjacolin** [comment]
+1 to move some section to a new developper manual in the QGIS-Doc.
