### ISSUE TITLE
[FEATURE][processing] Add overlay option to GridLine and GridPolygon

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1631]
Original commit: https://github.com/qgis/QGIS/commit/01cd784ee744e09760ee76f1ac883236357e3376 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by ghtmtt** [comment]
I cannot see any changes that are not described in the current ``Create Grid`` algorithm. This issue was opened because overlays have been added, but overlays are already described: 

https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vectorcreation.html#qgiscreategrid

@DelazJ if ok for you I'll close this issue

**Comment by DelazJ** [comment]
Agreed. Fixed in #2363
