### ISSUE TITLE
Map setting variables (map item) are not mentioned in the Users Manual

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS-Documentation#1804]

**Comment by DelazJ** [comment]
Isn't it covered in the first paragraph of http://docs.qgis.org/2.18/en/docs/user_manual/print_composer/composer_items/composer_items_options.html#variables? 
What however puzzles me is the second paragraph which refers to [composition-level variables](http://docs.qgis.org/2.18/en/docs/user_manual/print_composer/overview_composer.html#variables) being modifiable instead of composer item level's

**Comment by SrNetoChan** [comment]
@DelazJ  You are right. I will review it ASAP.
