### ISSUE TITLE
Large images are hard to read and it's not possible to click to enlarge

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS-Documentation#1883]
This is a problem when the image is too big, and is shrink to fit the documentation content space, but then it becomes hard to read.

In QGIS website, if you click an image, it will show the image in full resolution in the browser (although you will need to go bad to go to the page you were.

A better solution would be to introduce some kind of modal images:

https://www.w3schools.com/howto/howto_css_modal_images.asp

**Comment by rekjuh** [comment]
@SrNetoChan @DelazJ I stumbled upon this issue and decided to give it a go. Implementing the modal images is aesthetically pleasing but includes imho unnecessary amount of code considering what it does. My solution would be adding few lines of HTML for the images that suffer from scaling down. The HTML code would allow opening the image in new window (.rst doesn't support that). So it would be for example:

    .. raw:: html

        <html>
        <div align="center">
        <a href="img/file_name.png" target="_blank">Click to enlarge.</a>
        </div>
        </html>

The other option would be adding ":target: img/file_name.png" to the pictures to make them clickable. But that would open the image in the same window so it becames a bit frustrating for the user.

Tell me what you think.

**Comment by DelazJ** [comment]
@rekjuh Thanks for willing to help fix this 👍 . Technically speaking I'm unable to understand how your changes would impact the current process. Where would that lines land?
My "concern" is if this is still an issue. Do we still have images that are shrunk and unreadable (we meanwhile have enlarged the page width - [3.4](https://docs.qgis.org/3.4/en/docs/training_manual/map_composer/map_composer.html#basic-fa-adding-a-legend) vs [3.16](https://docs.qgis.org/3.16/en/docs/training_manual/map_composer/map_composer.html#basic-fa-adding-a-legend))?
> The other option would be adding ":target: img/file_name.png" to the pictures to make them clickable. But that would open the image in the same window so it becames a bit frustrating for the user.

This is not different from adding `:width: xxx` to the images, right? See eg the 3.16 image above can be clicked

**Comment by rekjuh** [comment]
Thanks for the quick reply @DelazJ !

Those lines would be underneath a picture, like so:

        .. figure:: img/rscript_folder.png
           :align: center
           :target: img/rscript_folder.png

    .. raw:: html

        <html>
        <div align="center">
        <a href="img/script_folder.png" target="_blank">Click to enlarge</a>
        </div>
        </html>

And the output would be:
![3rdparty-example](https://user-images.githubusercontent.com/87303508/133772613-0b26d30b-2f43-4cd1-a214-12ac925cf4bd.png)

I'm with you about the concern if this is an issue or not. The 3.16 page width is definitely an improvement. But I was thinking if I should go through the User guide and see if there are images that need "solving" to make sure that closing the issue is justified.

And yes, the :target: solution is pretty much the same as adding :width:

**Comment by DelazJ** [comment]
@rekjuh My choice would be to keep things as simple as possible and not add too much code in the rst files (and asking any contributors to do that for the images they pull in). IMHO Easier to add :width: than a snippet they'd have to update reference in. And if the image is well resized in the original page, people wouldn't to see it in a larger context.
Also, there still is possibility to right-click and open the image in a new page, if people want.
> But I was thinking if I should go through the User guide and see if there are images that need "solving" to make sure that closing the issue is justified.

That would be welcome. There might still be "unreadable" images, due to how they were taken or that we miss when adding the :width: thing (at the time the focus was more on larger images showing the whole QGIS interface than those of a single dialog, less problematic imo)
And we'll be safe while closing this report.

**Comment by DelazJ** [comment]
@SrNetoChan Is this still valid issue?

**Comment by SrNetoChan** [comment]
I believe this is still relevant in some cases.

Guys from Mergin Maps start using this:

https://francoischalifour.com/medium-image-zoom/

But... Either this is integrated into readthedocs itself, or currently I would be against adding too much customisation to our docs, as we know how it ends :-)

So, @DelazJ , I would keep this closed for now.
