### ISSUE TITLE
[FEATURE] Color settings for north arrow decoration

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1898]
Original commit: https://github.com/qgis/QGIS/commit/1445505a42a2d5a58e05ee1dc2bef0a7c600f6d4 by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by Hackingforlife** [comment]
hey @DelazJ ,@QGIS-feature-tracker, i would like to take on this issue. i also wanted clarification on what is required therein?

**Comment by DelazJ** [comment]
@Hackingforlife not sure I understand the kind of requirements you are looking for. The issue here relates to the North Arrow dialog from the View menu, so the idea would be to document the [whole dialog](https://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html#north-arrow). Otherwise there are docs writing guidelines at https://docs.qgis.org/testing/en/docs/documentation_guidelines/index.html
If ever I misunderstand your question, please clarify.

**Comment by Hackingforlife** [comment]
Thank you....you actually got it right...thanks again

**Comment by DelazJ** [comment]
Fixed in #2699
