### ISSUE TITLE
[FEATURE] Add outline and color opacity settings for scale bar decoration

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1899]
Original commit: https://github.com/qgis/QGIS/commit/83e8ecec453d2f96e5d93f5356fda922c4204cf6 by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by Drewfore** [comment]
@DelazJ do you mind if I have ago at this one as my first attempt?

**Comment by DelazJ** [comment]
@Drewfore, my pleasure. Please do!

**Comment by Drewfore** [comment]
Thanks @DelazJ I made my changes and submitted a pull request. https://github.com/qgis/QGIS-Documentation/pull/3248
I was not 100% sure on how I am meant to relate this issue and my PR to each other? Should I have mentioned the issue number in my PR comments?

**Comment by DelazJ** [comment]
@Drewfore Mentioning a pr/issue number in one of them automatically creates links between them. Now, you can do more, ie add text like `fix #1899` or `fixes #1899` or `close #1899` or ... either in a commit (too late, now) or in the pull request first message (my preference) so that when we merge your changes, they close this report automatically.

**Comment by Drewfore** [comment]
Thanks - I think I understand, so best practice would be to mention the issue number in my comments at the pull request stage. This links the PR with the issue automatically?

I mentioned the Pull Request number in the comments of the issue, I can see the hyper link in the comments above back to the PR. Does that mean they are linked? Or is there additional work I need to link them?
