### ISSUE TITLE
GUI naming conventions in guidelines

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS-Documentation#1901]
Sometimes in docs we name different thing to GUI widgets. For example:

- Dialog, Window;
- Field, text field, text box;
- Dropdown menu, Drop-down menu, Combobox;
- Tab, Panel;
- (In properties panel) group, section (of option);
...

Would be nice if we could write some lines in the guideline to clarify how to correctly mention certain widgets.

**Comment by DelazJ** [comment]
Except spelling error, I'd like to keep different words to name the same thing as long as they fit. Better use synonyms than same word in all the doc, imho

**Comment by yjacolin** [comment]
@delazJ it seems that this ticket is not about not using synomyms but rather the way we wrote some word in different way. I am +1 for using synonyms for the same idea than you.

**Comment by SrNetoChan** [comment]
@DelazJ I disagree about using synonyms for widgets and tools in technical writing. IMHO, this makes it difficult to the users to follow the documentations and instructions if they aren't aware of all the synonyms. For me, that is the main reason why I think it would be important to standardize the terms as much as possible.

But if it's only me, we can just close this ticket and carry on :-)

**Comment by pcav** [comment]
Agreed with @SrNetoChan : synonyms are obligatory in some lang (luckily not much so in EN), and always detract from clarity. Better avoid them.

**Comment by DelazJ** [comment]
uhmmm... Sorry but I still fail to see where the issue resides (maybe because I'm unconsciously translating them and _selfishly_ do not see issues for _my_ localized end users).

As far as I can say, tab vs panel issue (the only place I find misuse in the above list) has been solved or at least, is an ongoing work.
Except "combobox" that is a kind of technical word, aren't these words of common usage? Having to use "window" three times in three consecutive sentences (_remember the recent issue with composition-item-level or something like that_) while I can use another word is not that fun (for my selfish writing perspective 😠  ).

Anyway if there's an issue, let's see how it could be fixed. What are/could be the proposed solution(s)? Maybe that would make things clearer _for me_.

**Comment by diethard2** [comment]
It has been a while since I updated the guidelines, but I will have a try.
I propose to add a chapter "Preferred GUI naming" to guidelines, later it can be renamed to "GUI naming conventions", I will name the rest file "naming.rst".
The intention of this chapter is to help the writer to find the correct word to use or an accepted synonym. 

It starts with a table with three columns.
Each row holds in the first row the preferred name of a gui element, the second and third column provide accepted synonymes.
Only the first column has a referenced explanation.
If the explanation is already available in the user manual, than it refers to that section, otherwise a short explanation is included in this chapter.

I foresee that in some languages they have a different no of synonyms.

**Comment by diethard2** [comment]
I created a python script that reads a list of names and counts how often these appear in the rest documents, so I can figure out which is used most often.
A result of this compare; "radiobutton" (30 found) compared to "radio button" (11 found) so It seems "radiobutton" is the preferred way of naming this widget item! But.. a search on internet reveals you should write it as "radio button". This would mean the 30 instances of radiobutton should be renamed.

**Comment by havatv** [comment]
@diethard2, are you still motivated to work on this one?

**Comment by anitagraser** [comment]
Time to close this?

**Comment by SrNetoChan** [comment]
Yes. I would say so.
