### ISSUE TITLE
[FEATURE] History for attribute table form view display expressions

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2084]
Original commit: https://github.com/qgis/QGIS/commit/63d0a91566fe2593d8980ce6df5c6d4cbfb3ed8d by m-kuhn

It's possible to re-use the last 10 display expressions in the form view
of the attribute table.

The expressions will also be persisted in the project file.

Using fields will now show field aliases instead of column names where
available.

**Comment by DelazJ** [comment]
@m-kuhn from what i understand in
> Using fields will now show field aliases instead of column names where available.

If I set an alias on a field (in Attributes form tab) and double-click on it in any expression builder dialog, instead of the name of the field, it should show the alias. Am I right? In which case I'm afraid this feature does not work.

**Comment by m-kuhn** [comment]
It's about the combobox to define the preview expression for features within the attribute table.
What do you think, would it be desirable to have aliases more present as well in the expression builder (I think completely replacing there would be an overkill).

![image](https://user-images.githubusercontent.com/588407/37560795-61ac4ef0-2a3f-11e8-8ea0-eb2ecb165b11.png)

**Comment by DelazJ** [comment]
Images are always more than thousand words 👍 . Thanks.
> What do you think, would it be desirable to have aliases more present as well in the expression builder (I think completely replacing there would be an overkill).

I don't know if it'd be an overkill (you mean in the resulting expression, not in implementing it, right?), as long as aliases are used as alias and not as comment (see screenshot above 😃 ). But I think it could be nice sometimes to have human readable fields instead of some cryptic names with underscores ;), especially when you get back to old project with not frequently used data.
I recall a discussion/request on this (from Andreas?), reason why i first thought this was its implementation.

**Comment by m-kuhn** [comment]
In the expression builder, we have the list of fields in the tree view on the right. I guess that's where it would be nice to see the alias. Maybe list it as `Alias (field_name)` and/or with the field name in the tooltip.
In the expression itself aliases should at least be allowed (I asked for that some time ago on the mailing list and the general feedback was positive). The biggest doubts I have is for what happens when one double-clicks a field name in the treeview -> insert alias or field name?
An additional nice feature would be some tooltip within the editor to see field name / alias / other metadata when hovering over the text in the expression.

**Comment by DelazJ** [comment]
> In the expression itself aliases should at least be allowed (I asked for that some time ago on the mailing list and the general feedback was positive). 

It's implemented. Writing the alias instead of field name works. 
> The biggest doubts I have is for what happens when one double-clicks a field name in the treeview -> insert alias or field name?

My position above was to insert alias, which would be coherent or easier to understand if that alias is shown in the middle panel as you suggest : `Alias (field_name)` (my preference) or with tooltip. 
> An additional nice feature would be some tooltip within the editor to see field name / alias / other metadata when hovering over the text in the expression

\+ 1. And autocompletion...

**Comment by havatv** [comment]
If there is anything to document here, it would be nice to get input on what and where.

**Comment by m-kuhn** [comment]
I think a general description of the "display expression" in the "form view" is completely missing.
The form view shows a list of features on the left, the text shown in there is configurable with the display expression, which can be changed with [the button](https://github.com/qgis/QGIS-Documentation/issues/2084#issuecomment-373959329) on top of the list.
https://docs.qgis.org/3.10/en/docs/user_manual/working_with_vector/attribute_table.html#table-view-vs-form-view
This particular new feature in here might be worth a single sentence in a short paragraph about this topic.
