### ISSUE TITLE
[needs-docs] Rework arrangement of buttons in categories tab in
metadata editor to make their operation more self-explanatory
for users.

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2346]
Original commit: https://github.com/qgis/QGIS/commit/cd24adbf9e07253227574c290c76b51da791601c by nyalldawson

Also add tooltips to the buttons describing their function, and
allow the buttons to operate on multiple selected rows at once.

Fixes #18090

**Comment by nyalldawson** [comment]
This was tagged as needs docs in case screenshots need updating. Should I be using needs docs for commits like this?

**Comment by DelazJ** [comment]
Yes, you should.
My concern here is that i'm not sure we want to describe each sub-tab of the metadata tab.

**Comment by SrNetoChan** [comment]
For what I can see, for the users manual, there is no screenshots of the Metadata Editor. There is only a brief description of each tab purpose. And the "Identification" tab is mentioned as "Data Identification"

**Comment by DelazJ** [comment]
>For what I can see, for the users manual, there is no screenshots of the Metadata Editor.

They are still welcome. But I think a screenshot makes sense here if the fields are filled. Maybe now that every OS is publicly allowed for screenshot, we can expect inputs from people that use this feature...

> There is only a brief description of each tab purpose.

Yes when I tackled this area, I didn't feel like describing each sub tab (me lazy? noooo!) and actually didn't know what I'd have written more for most of the options. Filled screenshots (that i do not have) are better candidates imho.

> And the "Identification" tab is mentioned as "Data Identification"

Fixed in https://github.com/qgis/QGIS-Documentation/commit/e5c3187188354fe3396d78b0dd49b31edcf0c2f7

**Comment by havatv** [comment]
This issue has to to with an update that does not affect the current documentation.
So why don't we close this issue and open a new (and more specific) issue requesting documentation of the Metadata editor (that can be referenced from both layer and project properties).
