### ISSUE TITLE
QGIS server (linux debian) reference configuration file

### ISSUE THREAD

**Issue by rbonnefoi** [qgis/QGIS-Documentation#2389]
Dear all,

I notice there were to pages about the qgis server configuration file for Linux / Debian in the "testing" documentation, which are partly contradictory:

- §12.1.3 of the page https://docs.qgis.org/testing/en/docs/training_manual/qgis_server/install.html
- https://docs.qgis.org/testing/en/docs/user_manual/working_with_ogc/ogc_server_support.html#qgis-server-installation-on-debian-ubuntu

I think it would be safer to merge both examples (or even page) and to:

- correct in the first page the `SetEnv` commands, replacing them by the `FcgidInitialEnv` directive,
- insert in the latter a default `FcgidInitialEnv PGSERVICEFILE` command, which is, in my opinion, a very useful directive.

Anyway, many thanks for the work done by the whole qgis developing team.

Remi.

**Comment by DelazJ** [comment]
@rbonnefoi Could you please clear the cache of your browser and check again (your second link should not be valid as this part of the doc has been refactored) or look from https://docs.qgis.org/testing/en/docs/user_manual/working_with_ogc/? Thanks

**Comment by rbonnefoi** [comment]
Ok, I understood I was referring to an osbolete page, which is still reachable. Maybe you should delete the former version or use a redirect page to avoid misundestandings / misconfigurations.

Anyway, my other questions are still valid in my opinion:

- the need to mention the `FcgidInitialEnv PGSERVICEFILE` command in the default configuration file

- the need to merge (or redirect from) the training manual page to the user manual page.

**Comment by tudorbarascu** [comment]
@rbonnefoi Thanks for looking into those.
I think that mentioning the ``FcgidInitialEnv PGSERVICEFILE`` in the default configuration file is optional 
and if it exists or not is a matter of taste (this is because the demos etc. are not with postgresql). So, they're only there to show that it's possible.

Also, the training manual shouldn't be merged with the user manual as they have other scopes.

The ``SetEnv PGSERVICEFILE`` part should work as well as the ``FcgidInitialEnv PGSERVICEFILE``, doesn't it work for you?
I think the actual configuration should promote a little flexibility but we're opened for pull requests :smile:

Thanks again for raising this.

**Comment by rduivenvoorde** [comment]
I will  clean up current testing web folder. The process of building on one server and then rsyncying to the actual webserver does indeed not cleanup old stuff.

**Comment by havatv** [comment]
Can we close this?

**Comment by rbonnefoi** [comment]
Definitely.

Thank you very much.

Regards.

Rémi

Le dim. 27 janv. 2019 à 11:32, Håvard Tveite <notifications@github.com> a
écrit :

**Comment by havatv** [comment]
Thanks for the quick feedback, @rbonnefoi !
