### ISSUE TITLE
SAGA toolbox help buttons 403/404 errors

### ISSUE THREAD

**Issue by hbgcn** [qgis/QGIS-Documentation#3068]
## Description
Help buttons in SAGA tools accessed from the processing toolbox open webpages with 403 or 404 errors.
These are from clicking the help button on the window that opens when double clicking on a SAGA tool.

QGIS 3.2.3 on windows 10 64bit. 

The documentation (and any kind of description for the tools) is therefore harder to reach and has to be searched for.

## Checklist

- [ ] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [ ] I have added a link to the page concerned by the issue

**Comment by DelazJ** [comment]
I don't have SAGA installed. Can you provide the kind of link that is returned by the help button before the failure, please? Thanks

**Comment by hbgcn** [comment]
Hi, Here is such a link:
https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/saga/rastertools.html#sagaaveragewithmask2
These are from clicking the help button on the window that opens when double clicking on a SAGA tool.
I forgot to mention I am using windows 10

**Comment by DelazJ** [comment]
Hi, 
@hbgcn can you try with QGIS 3.4? I've been told that [things have changed](http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-Using-help-button-from-a-third-party-Processing-algorithm-td5381633.html). I don't expect it works with these algs but could you please report:
- whether help button is available within saga algorithms dialog?
- in which case, what is the page returned for the algorithm you previously tested?
- and what is returned if you use the help button of one of the algorithms mentioned at https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/saga/index.html?
- also what's your saga version?

Thanks.

**Comment by hbgcn** [comment]
Hi @DelazJ ,

- There is a help button on all SAGA tools. 
- When clicking the help button on a tool that is in the help list you provided, it does open a valid web page, although it does not scroll down to the algorithm (on firefox and chrome, win10x64). 
    Here is the link that opens with the help button on the Raster Buffer tool (not in the help list): https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/saga/rastertools.html#sagarasterbuffer
- The docs.qgis link you provided works fine.
- I recently used OSGEOW to uninstall everything and install 3.4 (I was having issues with different older versions not working). My SAGA install should now be the stadard one. It seems to be 2.3.2 (from looking at the shortucts in my "start menu")

Furthermore, I noticed that the algorithms don't have the same name on the web doc page and on the Processing Toolbox in qgis. For example, "raster" in qgis is replaced by "grid" on the doc. So the "raster buffer" algo doc page is actually "grid buffer". This may be why some SAGA help buttons can't redirect to the correct doc.

**Comment by havatv** [comment]
Should the documentation be adapted (change file names and directory names according to the new naming an organisation of the saga algorithms in the processing toolbox), or should the (SAGA / processing?) code be changed.

**Comment by DelazJ** [comment]
@hbgcn thanks. I expected these answers. 
@havatv my position, and i exposed it in the two mailing lists i raised the question (see link in previous comment), is that we should remove saga docs from our docs and rely on saga own docs. But i got almost no reaction/decision from that. I'll raise it a last time in psc list. 
>Should the documentation be adapted (change file names and directory names according to the new naming an organisation of the saga algorithms in the processing toolbox), 

Too much effort for what it's worth imho. it means that documenters install saga (don't forget that it's no more installed by default), and for each existing alg, find and replace the right name (to fix the issue reported by @hbgcn) but more important, complete the list and document these algorithms because most of them only list default values. Given the low working force in docs team and all the pending issues for QGIS native functionalities, spending time on documenting a third party plugin looks like a suicide to me. 
I've reviewed the recent update of Processing and i can tell you it's a lot of work. 
Saga already has a doc. Let's see with them what's needed to use their docs. Grass alg doc is open from within Processing. 
> or should the (SAGA / processing?) code be changed?

Yes, to open SAGA docs pages. 
Ps: i say saga but it's valid for R, Taudem, LasTools, OTB
