### ISSUE TITLE
Dead link in data_capture

### ISSUE THREAD

**Issue by SylvainLan** [qgis/QGIS-Documentation#3125]
## Description

Hi all, 

I am beginning to read your great doc, and just wanted to point out that there is a dead link in `data_capture.rst`, [here](https://docs.qgis.org/2.18/en/docs/gentle_gis_introduction/data_capture.html#further-reading)

There are also some typos in the french translation, I think I could make a PR with those I find but I can't find where it is in the repo, could someone point me towards it ? 

## Checklist

- [x] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [x] I have added a link to the page concerned by the issue

**Comment by havatv** [comment]
The following link is ok: http://www.k12science.org/curriculum/waterproj/S00project/miami2000/miamiriverfinal/
I guess it should be fixed in the release_2.18 branch.

**Comment by DelazJ** [comment]
@SylvainLan translations are managed in a different manner, not directly in the source. The best way is to become translator and push your changes directly. See https://qgis.org/fr/site/getinvolved/translate.html#becoming-a-translator 
If you need more info, do not hesitate. 
Link is fixed in source, hence closing the report. Merci.
