### ISSUE TITLE
Problems with Sphinx Theme

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS-Documentation#3142]
## Description

This issue pretends to gather know issues in the current documentation formating, mostly dependent of the Sphinx theme. This way, either we can fix the current theme, or we can try to use a new theme that fits our needs.

The current theme as the following know issues:

- [ ] Images don't have any border or shadow that helps it stand in the middle of the text.
- [ ] Images in lists don't have any margin to the text.
- [ ] Fullscreen images are hard to preview, because there is no pop up when you click a message. (see #1883)
- [ ] Search is not working properly on Testign documentetaion #2059
- [ ] Tables don't have margins regarding the text when there is no caption.
- [ ] (Edit and add more)  

## Checklist

- [ ] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [ ] I have added a link to the page concerned by the issue

**Comment by havatv** [comment]
Regarding images and border / shadow / ...
Adding padding / margins for all images is not a good idea.  In the QGIS documentaion, images are used for large illustrations (including screen shots), but they are also used for showing buttons / icons from the user interface.  The last category of images are often included in the text, and we would probably not want padding / margins there, while for the first category we would want to have margins / padding.
So for perfect formatting, I think we would need to have to "classes" of images - one for icons and one for figures.
Could .figure be used instead of .image for large images that are used as figures?
http://docutils.sourceforge.net/docs/ref/rst/directives.html#figure

**Comment by DelazJ** [comment]
Tables are also concerned by text being too close. And from what i can see, both images and tables have this kind of issue when they do not have caption; the next paragraph is then too close while with a caption, there seems to be more spacing.

**Comment by havatv** [comment]
My point is, that if we avoid using .image for our figures / screen shots, we can probably use CSS to add padding / margins.

**Comment by SrNetoChan** [comment]
@havatv I may be wrong, but don't we use figures already? If not, we should. Anyway, I think the inline images and the other images can always be separated in CSS anyway, but I'm nowhere near to understand enough of CSS and HTML.

I was not aware that the figures problem was only happening when there was no caption. I read somewhere that, for documentation, figures and tables should always have a caption. That's what I normally do. so, maybe that is a better fix, even when the caption looks unnecessary. Figures with caption really help the reader to quickly browse the docs.

Added the tables problem to the list.

**Comment by ghtmtt** [comment]
Actually we are using a mix of  ``.. image::`` and ``.. figure::``.

Having a caption (with the ``figure``) directive resolves the margin problem. But this forces to always add a caption: while sometimes it is perfectly useful, other times having a caption is not what the writer wants. 

Adding a `top` and `bottom` margin in the CSS file seems solving the problem.

**Comment by havatv** [comment]
I was not precise - .figure is used for figures, but also .image.  If we want to have general rules for how to present images that are used as figures, we need to differentiate them from images that are integrated into the text.

**Comment by DelazJ** [comment]
> Having a caption (with the figure) directive resolves the margin problem. But this forces to always add a caption

According to http://docutils.sourceforge.net/docs/ref/rst/directives.html#figure caption is optional. Or do you mean by using the caption trick to solve the problem?

> while sometimes it is perfectly useful, other times having a caption is not what the writer wants.

Agreed. The missing caption is mainly observed in training manual. And imho this makes sense because the screenshot often represents the comment just above so a caption would be very repetitive and not really relevant.
