### ISSUE TITLE
[needs-docs][ui] Remove save as action from the project toolbar

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3154]
Original commit: https://github.com/qgis/QGIS/commit/3fa4d6a22fb6df0d18e2012700804cef1c6f1b6d by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by felixfeckler** [comment]
@DelazJ i think this one can be closed.
In https://docs.qgis.org/testing/en/docs/user_manual/introduction/project_files.html#project-files there is no real reference to the toolbar, and since the "save as..." is still available in the menu, i dont think we have to explicit state that it is not in the toolbar...
Also the image in the section is okay, since the toolbar is covered.

**Comment by DelazJ** [comment]
Good catch @felixfeckler
