### ISSUE TITLE
[needs-docs] Fix use of duplicate action name

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3188]
Original commit: https://github.com/qgis/QGIS/commit/83aa32cbf2f6ea9b978662a98547877da5b09196 by nyalldawson

(Properties is already used by project properties)

(cherry picked from commit 152b1b09ff0e45b30a72d53904437af032e8659e)

**Comment by lajunek** [comment]
@havatv don't want to spend too much time on 3.4, I see that the screenshots and texts in "The Vector Properties" are update. Do we really need to implement something into the docs here?

**Comment by havatv** [comment]
@DelazJ does not want us to spend time on 3.4, so just leave it. I leave it to @DelazJ to decide if this one should be closed.

**Comment by DelazJ** [comment]
> @DelazJ does not want us to spend time on 3.4

I did not say that @havatv. My point is that we should not spend time on 3.4 **documentation**, which is different from 3.4 **features**. A report for <3.4 can still be appropriate/relevant for 3.10 because the feature is still there. If it's the case my point is to document it in master only (no backport); if it's not the case, then close the report.

I think this issue is solved but I'll check when I have a git infrastructure.
