### ISSUE TITLE
Display a message bar for deprecated version

### ISSUE THREAD

**Issue by Gustry** [qgis/QGIS-Documentation#3452]
## Description

I see quite a few links on blog post/social networks/GIS.SE pointing to QGIS Documentation 2.8.
For instance today,  I saw a post on social network linked to https://docs.qgis.org/2.8/en/docs/user_manual/working_with_vector/expression.html

Can we had a kind of message bar about versions which are not maintained anymore?

Like Django documentation 1.8 which is not maintained anymore:
https://docs.djangoproject.com/en/1.8/

## Checklist

- [x] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [x] I have added a link to the page concerned by the issue

**Comment by DelazJ** [comment]
Agreed. I also often see references to old docs in forum. Might be because it's what their search browser returns by default so adding a mention might be good indeed.

**Comment by m-kuhn** [comment]
I have been working on the header.

But I think the point by @DelazJ is very valid. E.g. [when I search google for "qgis raster calculator"](https://www.google.com/search?q=qgis+raster+calculator) it takes me directly to the 2.8 docs. It's not even visible on Google.

What I could imagine instead is publishing a stable link to the latest stable version with no version included. This will be the page we want to be indexed on search engines. So currently we'd have a copy of 3.4 there, in the future that's gonna be the next LTR. Sometimes link will be out of date. But not that often and even if they are, we could fix that with some internal redirects. More often I think downstream will update their links (e.g. on gis.se someone notices it's broken and the link gets updated. Right now noone notices it's pointing to an old version).

**Comment by DelazJ** [comment]
Hi @m-kuhn 
Thanks for putting attention on this "backend" issue. Today, I again see someone add a 2.8 link in a forum discussion.
> What I could imagine instead is publishing a stable link to the latest stable version with no version included. This will be the page we want to be indexed on search engines. So currently we'd have a copy of 3.4 there, in the future that's gonna be the next LTR.

I don't know how indexing works. Would the URL with latest be shown when browsing the (currently) 3.4 docs or would it just be something we'd use behind the scene, at the server level, to redirect pages to the current LTR. IOW, would we show to the user, in the browser: https://docs.qgis.org/3.4/en/docs/user_manual/introduction/qgis_gui.html or https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_gui.html ?
I'd be in favor of using latest in the backend and not necessarily in the browser. but wonder if it'll be indexed that way.
> Sometimes link will be out of date. But not that often 

Not that often? Authoring most of these changes, I'm not sure they are as less frequent as you think... Just give a look to the left-side TOC from version 2.14 to testing. And remember it does not display internal chapters (and moves). You guys are developing QGIS too much/fast and keeping the old docs structure is not always easy/possible/sensible.
> and even if they are, we could fix that with some internal redirects.

Having vainly asked for years for a way to handle redirections (for help buttons), allow me to be a bit skeptic on this... :cry: 
> More often I think downstream will update their links (e.g. on gis.se someone notices it's broken and the link gets updated. Right now noone notices it's pointing to an old version).

A 2.8 link can be relevant for a discussion at a time and replacing that link with its latest correspondent may not be of the same interest (because feature had evolved meanwhile). Versioned docs are associated with a state of features, a context and using a dynamic, changing page like 'latest' can make history of discussions hard to understand. no?

**Comment by m-kuhn** [comment]
So there are 2 issues for what I can see:

 - People putting links to specific version documentation.
 - Search engines showing links to specific version documentation.

I think the second one is (at least partially) linked to the first one, because search engines tend to fill their indexes with links they find on the net.

To fix the first one we will have to convince people to link by default to "latest" (from my experience, linking to specific version docs is an edge case). Currently it's hardly visible that there is a "latest" redirect available. That's why I would suggest to change that, but I can see it's a two sided move.

Alternatively (or in addition), someone could also log into the search engine admin panels for our domain and manually remove all links to old versions (no idea who has access to that currently, maybe @rduivenvoorde knows more about that).

Maybe I'm also missing some other strategies like adding a sitemap or setting an http or html meta attribute to tag some pages as "archive versions", but that's out of my SEO knowledge league.

**Comment by havatv** [comment]
Deprecation warnings now appear in documentation for old versions. For 2.14 (https://docs.qgis.org/2.14/en/docs/) it shows: "Outdated version of the documentation. Find the latest one here."
So can this one be closed, @Gustry, @m-kuhn?

**Comment by m-kuhn** [comment]
Yes, they are shown.

I am a bit confused about the process, because what's shown there is not what I have done, but some other patching in the server config by @jef-n . The advantage of "mine" would be that they scroll with the text, if you directly link to a subsection of the docs you will currently not see the warning. It just seems a bit weird to wait 6 months for someone to do the job and then solve it in a different way the next day once it's done.

**Comment by jef-n** [comment]
> It just seems a bit weird to wait 6 months for someone to do the job and then solve it in a different way the next day once it's done.

Wel, not sure anyone waited for six month.  I didn't. I just noticed it when it got noisy here.  The advantage of "mine" is, that it doesn't need to be backported to several - otherwise long unmaintained - branches, have them rebuilt, and "update" the old documentation on the server - instead it's just a few lines in the apache config.

**Comment by rduivenvoorde** [comment]
FYI: rebuilding the old documentation branches is not preferable for non-english versions, because the transifex resources are not in sync anymore with those. I do not think I pull all translations into git if we branch a new version...

**Comment by m-kuhn** [comment]
The outdated translations are a convincing argument (backporting and rebuilding not so much, that has been done already here, sorry Jürgen ;) ), let's live with this version then.

**Comment by DelazJ** [comment]
Btw, I'm adding pulling translations from transifex into the old branch as a step when branching a new doc (https://github.com/qgis/QGIS-Documentation/projects/1)
