### ISSUE TITLE
startup.py path in documentation not the same than in QGIS 3.6

### ISSUE THREAD

**Issue by JaumeFigueras** [qgis/QGIS-Documentation#3722]
## Description

Page URL: https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/intro.html?highlight=startup#id7

the correct path in linux, is .local/share/QGIS/QGIS3

I had malfunction on startup and asked in gis.stackexchane : https://gis.stackexchange.com/questions/322007/qgis-3-6-startup-py-not-executed?noredirect=1#comment524036_322007

I do not know how to touch the docs directly and make a PR.

Thankyou.

**Comment by DelazJ** [comment]
Hi @JaumeFigueras 
Thanks for reporting. I can see that the fix is mentioned in different threads on GSE for a month and unfortunately not reported in the repository until now. Thanks very much again. Fixing the mistake in the docs will for sure save time for others who will try.

If you want to try to fix it (btw, the part after QGIS3 would need to be removed for other OSes also), you have in the footer of the [page]( https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/intro.html) a `fix me` link that opens the source file in github, in edit mode. You can then modify and open a PR. More details at https://docs.qgis.org/testing/en/docs/documentation_guidelines/first_contribution.html and we are around if you need help.

**Comment by JaumeFigueras** [comment]
Thanks lot the information @DelazJ I will follow the guidelines you provided to make a PR.
