### ISSUE TITLE
[FEATURE][layouts] Add a dedicated toolbar action to create north arrows

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3832]
Original commit: https://github.com/qgis/QGIS/commit/0ccc8f15ff3aa613f1a0a37c7809953533bf8a89 by nirvn

This is a shortcut to adding a picture item, setting it to a north arrow
picture, and linking it with a map. The end result is identical, but it's
much easier for new users to understand if we expose it as an explicit
"North Arrow" item.

Even experienced users will likely appreciate the improved workflow,
including automatically linking the picture rotation to a sensible
default map choice (if a map is selected, it's used. If not, the
topmost map item under the newly drawn north arrow is used. If there's
none, the layout's 'reference map' (or biggest map) is used as a
fallback)

Fixes #30162

**Comment by DelazJ** [comment]
Since this is a shortcut of image item, meaning same properties and so on, no need to add a dedicated page. Mentioning the tool at https://docs.qgis.org/testing/en/docs/user_manual/print_composer/composer_items/composer_image.html#the-picture-item and in the page title (eg `The picture and north arrow items`) should do the trick imho.
