### ISSUE TITLE
Service area (from layer) travel time cost doesn't work as documented

### ISSUE THREAD

**Issue by anitagraser** [qgis/QGIS-Documentation#3898]
## Description

Page URL: https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/networkanalysis.html#id10

The documentation states that the travel cost parameter should be in hours: 

> Travel cost [number]
> The value is estimated as a distance (in the project map units) when looking for the Shortest path and as time (in hours) for the Fastest path.

However, the resulting areas are much too small. Based on my experiments, I'd say that the unit should be seconds. 

It would be great if someone could cross-check or if a dev could confirm / clarify.

**Comment by rduivenvoorde** [comment]
Mmm, if I'm correct @alexbruy created/automated these docs with some script initially. I'm not sure IF or how these are being updated though. 
Could it be that the interface changed, but the docs not?

**Comment by anitagraser** [comment]
@rduivenvoorde if I interpret the GIT history correctly, then Harrissou wrote these docs in https://github.com/qgis/QGIS-Documentation/commit/9e3e047cce2d262d5affbd3a289fb36cf7b23357

**Comment by DelazJ** [comment]
Hi,
@rduivenvoorde since the grant proposal to update the processing docs (2017?), these are manually updated. I'm not sure there were any automatic updates after the initial push. And Afair, the network algorithms were not documented in 2.x, reason why they were still missing after the Processing docs update.

@anitagraser yes these additions are mine. Looking to the code, I found https://github.com/qgis/QGIS/blob/8a3c7b14c367771d096b4a6d006aa3c4b1017dd5/python/plugins/processing/algs/qgis/ServiceAreaFromLayer.py#L226 (with a `1000/3600` conversion so I guess there's something with seconds) then https://github.com/qgis/QGIS/blob/master/src/analysis/network/qgsnetworkspeedstrategy.cpp (that I can't understand). But doing tests with rounded values (cost 3600, speed 10km/h) the results on a straight line (9961m) look more like seconds related than hours. So I think you are right.
But it would be nice to have confirmation from devs and adding these units in the GUI could help clarify things.

PS: (not to discard myself) I especially introduced this [pull request](https://github.com/qgis/QGIS-Documentation/pull/3203) with a call for review from those who (might) use or know the tool ;)
_Morality: we really need more active pairs of eyes to review docs contribution._

**Comment by DelazJ** [comment]
Looking to it closer, I think what might lead to this error is that the shortest path tool (eg, point to point), with _fastest_ parameter, outputs the cost in hours. Documenting them altogether, I wrongly supposed they were using the same units.
It could be nice that we homogenize the units between the networks tools (inputs and outputs).

**Comment by anitagraser** [comment]
Thanks for testing and for adding the information about the expected units to the GUI, @DelazJ! 

Yeah, I definitely remembered the PR from last year and how hard it was to get feedback from people who know the code.
