### ISSUE TITLE
Allow to define multiple field pairs for relations (composite keys)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4087]
Original commit: https://github.com/qgis/QGIS/commit/9b4cb6f502c4f01641e0f0f7dd2ff3ac232c110f by web-flow

[FEATURE] allow to define multiple field pairs for relations (composite keys)

**Comment by lajunek** [comment]
@3nids Dear Denis, we only have a short explanation about working with the relationship strength "Composition". 
    "Relationship strength sets the strength of the relation between the parent and the child layer. The default Association type means that the parent layer is simply linked to the child one while the Composition type allows you to duplicate also the child features when duplicating the parent ones."

**What can the user do with this setting in detail?** I tried to copy a feature with its related features and the relationship strength composition. Failed :-( .  Thanks for helping us!

**Comment by 3nids** [comment]
Hi, I will let @m-kuhn or @signedav reply to this one as they have worked on the relation strength. The work I did was only the support of multiple keys.

**Comment by signedav** [comment]
Hi there

On composition strength the children are duplicated with the parent by using the duplicate function. On copy/paste this is AFAIK not (yet) integrated. 
Since 3.14 the children are deleted cascade on composition strenght. 
This is mainly nice, when you have many-to-many relations with association-tables.

**Comment by lajunek** [comment]
Hi,what Kind of Funktion is this. Are you talking about PostGIS? Or SQL?Regards, LarissaVon meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: signedav <notifications@github.com> Datum: 03.06.20  20:08  (GMT+01:00) An: qgis/QGIS-Documentation <QGIS-Documentation@noreply.github.com> Cc: lajunek <l.junek@gmx.net>, Assign <assign@noreply.github.com> Betreff: Re: [qgis/QGIS-Documentation] Allow to define multiple field pairs
  for relations (composite keys) (#4087) 
Hi there
On composition strength the children are duplicated with the parent by using the duplicate function. On copy/paste this is AFAIK not (yet) integrated.
Since 3.14 the children are deleted cascade on composition strenght.
This is mainly nice, when you have many-to-many relations with association-tables.

—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/qgis/QGIS-Documentation/issues/4087#issuecomment-638369253",
"url": "https://github.com/qgis/QGIS-Documentation/issues/4087#issuecomment-638369253",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by signedav** [comment]
Hi @lajunek 

It's in the Relations settings in QGIS. It does not matter what data source you use. See the description here https://docs.qgis.org/3.10/en/docs/user_manual/working_with_vector/attribute_table.html#creating-one-or-many-to-many-relations

**Comment by agiudiceandrea** [comment]
hi @3nids, I'm trying to use the the multiple keys relation introduced by you with PR https://github.com/qgis/QGIS/pull/31178, but it seems not working or at least it not work as I expect...

If I have two tables, say "parent" and "child", with "p_field1" and "p_field2" fields in the former and "c_field1", "c_field2", "c_field3" for the latter and I add a relation between "parent" and "child" with "p_field1" related to "c_field1" and "p_field2" realated to "c_field2", I will expect that the "child" records related to the "parent" records will be the ones for which "p_field1" = "c_field1" AND  "p_field2" = "c_field2".

Instead the relation is set only for the first field: "p_field1" = "c_field1". So the second fields relation is not taken in consideration...

I've misunderstood anything?

**Comment by lajunek** [comment]
@DelazJ @havatv when using the identify tool for the child layer of a relation in QGIS 3.10 in the Identify Results one can open the feature form.  On my machine I don't have the information of the parent feature embedded in this form. Instead, there is another menu for the parent feature in the Identify Results. Shall I document this or is there a special setting which embeds the parent feature information into the feature form?
![grafik](https://user-images.githubusercontent.com/47246213/86513828-99a80880-be0d-11ea-9273-ac846a9b4a9b.png)

Regards, Larissa

**Comment by 3nids** [comment]
> Instead the relation is set only for the first field: "p_field1" = "c_field1". So the second fields relation is not taken in consideration.

@agiudiceandrea are you talking about the automatic definition of the relation?

**Comment by agiudiceandrea** [comment]
> are you talking about the automatic definition of the relation?

@3nids No, I'm talking about the manual defintion

![image](https://user-images.githubusercontent.com/16253859/86721634-76a47100-c026-11ea-961c-692696607da8.png)

Although a relation with two field pairs is set, it seems to me that only the first field pair is actually used in the relation.

**Comment by 3nids** [comment]
fix is here: https://github.com/qgis/QGIS/pull/37640
