### ISSUE TITLE
[FEATURE] [needs-docs] Add circular data dependencies (#30947)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4142]
Original commit: https://github.com/qgis/QGIS/commit/5b71e21613a81dd4c5a2aa0c4c45fe96a9aaa4c0 by mhugo

* [FEATURE] [needs-docs] Add circular data dependencies

**Comment by havatv** [comment]
@mhugo What should be documented? And where should it be documented?

**Comment by mhugo** [comment]
I thought nothing was documented about data dependencies. But it appears there is a small paragraph in the [documentation](https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/vector_properties.html#dependencies-properties). The question of circular dependencies that was disallowed and are now allowed is not covered in the documentation.

So, I guess this new PR does not require specifically a new documentation. The "needs-docs" tag can then be ignored.

However, ideally, since this is a feature not very easy to understand and manipulate, some more matter in the documentation would be welcomed in my opinion.

**Comment by havatv** [comment]
Thanks for the clarification, @mhugo. Documentation contributions by experts like you are welcome!

**Comment by lajunek** [comment]
@DelazJ Hi Harissou, I think we can close this issue

**Comment by havatv** [comment]
Perhaps @mhugo would like to add something about circular dependencies first?

**Comment by DelazJ** [comment]
I read the docs and have no idea what els should be added here...
