### ISSUE TITLE
No documentation about QLR format and loading layers

### ISSUE THREAD

**Issue by 3nids** [qgis/QGIS-Documentation#4399]
I could not find any documentation.
Is this missing?

**Comment by havatv** [comment]
@3nids, I found:
https://docs.qgis.org/3.4/en/docs/user_manual/introduction/general_tools.html#layer-definition-file
Do you have any suggestion for what more to document and/or how the existing text could be improved?

**Comment by 3nids** [comment]
I would fine it more natural in managing data source
https://docs.qgis.org/3.4/en/docs/user_manual/managing_data_source/index.html
and this section is pretty small :)

**Comment by havatv** [comment]
Moving: I can't see the advantage of moving it to the "Managing data source" chapter.  Where in that "chapter" would it fit?
But we should include links to the description of QLR files to make it more visible / easy to find. Where would it be natural to have these links?
Expanding: What more should be included in the description?

**Comment by 3nids** [comment]
> Moving: I can't see the advantage of moving it to the "Managing data source" chapter. Where in that "chapter" would it fit?
in opening data.

> closed this in #4402 7 minutes ago
sorry, I don't see any evidence of QLR files here

I still believe that the right place for the explanation is in opening data.

**Comment by havatv** [comment]
I hope we can solve this by providing a reference to this new "QGIS file formats" appendix in "opening data". Would you like to create a pull request on that @3nids, or should I put it on my todo list?

**Comment by 3nids** [comment]
sorry, I have no time slot to work on the docs for now

**Comment by DelazJ** [comment]
Sorry for being late on this. 
As a data type you can load in QGIS I agree that qlr doc (how to create/load it) should better stay next to the other supported formats. Also I don't think that the appendix should replace anything here; imho it adds more in-depth information but not necessarily how I would interact with the data. Last but not least that chapter is itself a hidden one you don't find in the default TOC and per se would be at the end of the docs.  
>  and this section is pretty small :)

This is all a mix of knowledge/interest/importance a writer has for a feature. It's up to those who know more to give a hand for more details if needed, hence @havatv's question 
>  Expanding: What more should be included in the description?

>  sorry, I don't see any evidence of QLR files here

Me neither. It's definitely not fixed by #4402. Maybe the issue should be reopened.

**Comment by havatv** [comment]
I agree that it should be reopened.

**Comment by havatv** [comment]
@3nids, is this issue ready to be closed, or must more be done.

**Comment by 3nids** [comment]
yes, all good, thanks a lot!
