### ISSUE TITLE
Improve Title Label decorator documentation

### ISSUE THREAD

**Issue by diethard2** [qgis/QGIS-Documentation#5018]
## Description
The icon needs to be replaced for the title label decorator and it is better that copyright and title label decorators have their own section. Now they are merged together and now I want to describe another decorator, it becomes a bit inconsistent. 
The icon for the title label decorator needs to be added to images, substitutions.txt and chapter substitutions of user guide. 

Page URL:

**Comment by DelazJ** [comment]
@diethard2 can you elaborate a bit? I can find the title label decoration icon in both the [ feature description section](https://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html#copyright-and-title-labels) and the [substitutions list](https://docs.qgis.org/testing/en/docs/documentation_guidelines/substitutions.html#print-layout) (though it should probably be also in the "other basic icons" section?
> Now they are merged together and now I want to describe another decorator, it becomes a bit inconsistent.

The reason why they are merged together is because those two dialogs are identical and we avoid duplicate description, translations, rewording (and probably updates with new widgets). And I'm not sure I get how it compromises the addition of a new decoration, here; there are already other decorations sections.

**Comment by havatv** [comment]
> @diethard2 can you elaborate a bit? I can find the title label decoration icon in both the [ feature description section](https://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html#copyright-and-title-labels) and the [substitutions list](https://docs.qgis.org/testing/en/docs/documentation_guidelines/substitutions.html#print-layout) (though it should probably be also in the "other basic icons" section?

It is not the same icon. The decorations icon is a big capital T (with a plus), while the |label| is a not so big capital T in a box (with a plus).
