### ISSUE TITLE
Pages not found in Manual

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#552]
There are wrong links in http://docs.qgis.org/2.8/fr/docs/training_manual/foreword/foreword.htm :
- http://linfiniti.com/dla (in #background section) return "article not found"
- training manual (https://github.com/qgis/QGIS-Training-Manual) and its license (https://github.com/qgis/QGIS-Training-Manual/blob/master/index.rst) stated under #license section no longer exist. Indeed, there's no qgis/QGIS-Training-Manual repository on Github.

**Comment by rduivenvoorde** [comment]
fixed by linking to our own online version (for what I know the linifini version is not online anymore), and by rephrasing the paragraph:

https://github.com/qgis/QGIS-Documentation/commit/52f0babbdd3bce73cd5de687871269f93e6122ed

and 

https://github.com/qgis/QGIS-Documentation/commit/d05c936e0945f79f98c794852263e847e3f44ffe

**Comment by DelazJ** [comment]
Thanks @rduivenvoorde 
I found later that my report was a kind of duplicate of #546. It should be closed now.
