### ISSUE TITLE
Document how to raise the limit for max number of files  opened

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS-Documentation#6012]
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [17101](https://issues.qgis.org/issues/17101)

Redmine category:documentation_and_help
Assignee: Yves Jacolin

---
see https://github.com/qgis/QGIS/issues/23964#issuecomment-495868956

**Comment by alexbruy** [comment]
Moved from the QGIS bugtracker as this ticket is about documentation. Hope in this repository it will get more visibility and more likely will be addressed.

**Comment by anitagraser** [comment]
If I read https://github.com/qgis/QGIS/issues/23964#issuecomment-495868958 correctly, the documentation should mention `prlimit` in addition or instead of `ulimit `.

According to [OReilly Hands-On System Programming with Linux by Kaiwan N Billimoria](https://learning.oreilly.com/library/view/hands-on-system-programming/9781788998475/)

>  prlimit differs from ulimit in the following ways:
> 
> It's a newer, modern interface (Linux kernel version 2.6.36 onward)
> It can be used to modify limits as required and launch another program that will inherit the new limits (a useful feature; see the following examples)
> It's a binary executable program in itself, not a built-in like ulimit is
