### ISSUE TITLE
An afternoon with the QGIS Training Manual

### ISSUE THREAD

**Issue by gbpalmer** [qgis/QGIS-Documentation#6400]
## Description

Submitted at suggestion of Etienne Tremaille

Here is a log of a few mostly happy hours spent in the training manual located at https://docs.qgis.org/3.16/en/docs/training_manual/index.html. Comments would be welcome. Gary. OS 10.15.7 (Catalina) on iMac Pro. QGIS 3.16.0-Hannover.

4.1.2 Click on the Add New Map button. There is no such button on the Swellendam window.

5.1.2 1. Click on the Select Features button in the Attributes Toolbar. 2. Click on the feature that was just created and the remaining buttons will become enabled. The remaining buttons do not become enabled.

5.1.5. If the roads layer is not in your map, then add it from the GeoPackage file training-data.gpkg included in the exercise_data folder of the training data you downloaded. At this point, I remember adding a portion of a GeoPackage file, but I don?t remember how. I am unsuccessful in using the menu Layer -> Create layer and Open Data Source. When I try to open the GeoPackage file I see a message that the file is read only. I try Menu Layer > Add Layer > Add Vector Layer >  file dialog > roads. This works. I feel a hint would be useful to avoid some flailing around. Just a note that we are adding an existing layer from the GeoPackage rather than creating a new layer would be helpful. Now I see the layer training_data_roads in the Layers box. It is checked and selected, it is the top layer, but no roads appear on the map. Now I will have to search back to where a vector layer was first imported from the GeoPackage. A numerical reference (2.2.3) and link would be useful here. I
delete the training_data_roads layer and try again. I use the Open Data Source Manager and click on the GeoPackage tab.  I add the roads, which appear on the map. Success, but painful and time-consuming success.

I still need the routes.shp file, so I try Menu > Create Layer > New ShapeFile layer. I select Geometry Type line and add the new field name in the dialog box. Error message: Layer creation failed: Failed to create file routes.shp: Read-only file system. Without the shapefile, the vectors for the path and track can not be added.

Page URL:

**Comment by DelazJ** [comment]
Hi @gbpalmer . Thanks for the report.
> 4.1.2 Click on the Add New Map button. There is no such button on the Swellendam window.

You mean there's no such tooltip (I see it was renamed "Add Map") or you did not find a tool with this icon (it should be there by default and is visible in the screenshot, otherwise check the "Add Items" menu). Not sure there's much we could do there.
> 5.1.2 1. Click on the Select Features button in the Attributes Toolbar. 2. Click on the feature that was just created and the remaining buttons will become enabled. The remaining buttons do not become enabled.

Not sure to get the report. I have the tools on the "Digitizing toolbar" enabled if I select a feature in edit mode. In certain circumstances you may have the (Undo/)Redo buttons still disabled but not sure that's a big deal. Anyway, I'll just remove these steps as I don't really see what they actually bring to the user
> 5.1.5 ...

Should be better now with #6413. Thanks.
