### ISSUE TITLE
Missing documentation for rotated ticks/annotation in grids for print layouts map items

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Documentation#6679]
## Description

The description of the "Frame" / "Follow grid rotation" group grid settings of the print layout Map item 
![image](https://user-images.githubusercontent.com/16253859/116228064-1ae1da80-a755-11eb-906b-974363df4506.png)

is missing from the relevant documentation page
18.2.2.6.2. Grid Frame
https://docs.qgis.org/3.16/en/docs/user_manual/print_composer/composer_items/composer_map.html#grid-frame

The feature was introduced since QGIS 3.16.0 with PR https://github.com/qgis/QGIS/pull/37041 by @olivierdalang

**Comment by Gutzeit555** [comment]
working on it

**Comment by Gutzeit555** [comment]
@Gutzeit555

**Comment by Gutzeit555** [comment]
Hello @olivierdalang,
I started working on a documentation for this and would like to ask you for help ;-). I have tried out the functions and read the descriptions at qgis/QGIS#37041 and qgis/QGIS#36904. Now I have written drafts and (as it seems a bit more complex to me) would like to ask you to read them first. This then still has to be integrated into the existing documentation-text.

Since you also added the possibility to format the text, a link to Chapter „[Formatting the label text](https://docs.qgis.org/3.22/en/docs/user_manual/style_library/label_settings.html#formatting-the-label-text)“ should also be included, right?

btw: On my computer the „Font“-button is a bit cut off (see pictures below)

**Frame:**
If you have selected a map rotation ("Main properties"), you can use "Follow grid rotation" to say that the frame should match this rotation. This only works with Interior and/or Exterior Ticks.
With "Ticks alignment" you can decide whether the ticks should have a fixed length (depending on „frame size“) or end where they intersect the outer edge of the frame („orthogonal“).
„Skip below angle“ can be used to prevent ticks that have a very small angle to the frame and therefore become very long (and maybe unclear).
To avoid overlapping in the corners, at „Margin from map corner“ a distance to the corners can be set up to which the ticks are not drawn.

**Coordinates:**
With "Follow grid rotation" the coordinates are aligned to a rotated grid. To rotate them as well, "Above Tick", „On Tick“ or „Under Tick“ must be selected for the coordinates direction.
With "Annotations alignment", the reference point for the coordinates can be set (see „Frame“). The same value should be used here as for the ticks.
„Skip below angle“ and „Margin from map corner“ can be used to avoid drawing overlapping and unclear coordiantes.

![Font-Button_](https://user-images.githubusercontent.com/61974701/143890820-9ad3796f-e64b-4a14-b81d-c5c476611987.png)

![QGIS-Version](https://user-images.githubusercontent.com/61974701/143890858-d2bb1e1d-4711-460a-a206-6fa7ec250502.png)
