### ISSUE TITLE
Branch documentation about API is not updated with point release

### ISSUE THREAD

**Issue by Gustry** [qgis/QGIS-Documentation#6758]
## Description

Looking at the page : 
https://qgis.org/api/3.10/classQgsVectorFileWriter.html#aa69d7084007503269158d425d2709a2e
which is designed for "3.10" shows only 

> QGIS API Documentation  3.10.0-A Coruña (6c816b4204)

at the top

In the meantime, 3.10 got new functions.
For instance, `writeAsVectorFormatV2` since 3.10.3

I think documentation on branch should be updated to reflect new/deprecated API, not only .0.

I hope I am in the good repository.

**Comment by DelazJ** [comment]
> I hope I am in the good repository.

Unfortunately, no! This repository only cares about https://www.docs.qgis.org/version/xxx contents.
Anything related to API ([C++](https://wwwqgis.org/api/) or [PyQGIS](https://wwwqgis.org/pyqgis/)) should first be reported to the [QGIS code repo](https://github.com/qgis/QGIS/issues) since this is the place that feeds contents of these websites, or in some circumstances to [pyqgis repo](https://github.com/qgis/pyqgis/issues).

**Comment by Gustry** [comment]
Can you transfer it ? 
Ok, I understood for next time.

**Comment by DelazJ** [comment]
No, not enough rights. @gioman can you help transfer this to the code repo, please? Thanks

**Comment by Gustry** [comment]
Doing it manually
