### ISSUE TITLE
[FEATURE] expression: align strpos behaviour with postgres

### ISSUE THREAD

**Issue by qgis-feature-tracker** [qgis/QGIS-Documentation#679]
Original commit: https://github.com/qgis/QGIS/commit/2a557db39d9e0823658ea1ebbaf2e499ac5e1421 by jef-n

Unfortunately this lazy coder did not write a description... :-(

**Comment by jef-n** [comment]
strpos used to return -1 for no match and indexes starting with 0 instead of 1.  It now is aligned with [postgres' strpos](http://www.postgresql.org/docs/9.4/static/functions-string.html) like many other functions.  See also [Addressing a discrepancy between substr and strpos](https://lists.osgeo.org/pipermail/qgis-developer/2015-November/040396.html)

**Comment by DelazJ** [comment]
The old behavior was not documented. This is a kind of "bug fix" and the help in expression tab is already updated with the right behavior. Shouldn't we just close this? Is it worth adding this in the doc?

**Comment by yjacolin** [comment]
Doc is for the last stable release, aka 2.14, so we need to focus on the behaviour of this release. So +1 to close it.

**Comment by yjacolin** [comment]
Close it.
