### ISSUE TITLE
QGIS Training Manual - Project Snapping Options

### ISSUE THREAD

**Issue by eboelcke** [qgis/QGIS-Documentation#7285]
The Form "Project Snapping Settings" has been changed at least since version 3.18. The new form does not contemplate "Map Units" as units any longer but it seems that directly takes the unit of measure corresponding to the projects CRS.
The form provides a per layer option of "avoid overlap" and a combo box on top with the options of: avoid overlap; allow overlap on active layer; and Follow advanced configuration. It would be nice to know what's the interaction among these controls.
The Form has on top three buttons for: topological editing; snapping on intersection; and self-snapping. It would be nice to explain when are they on or off.
Chapters [14.3.4](https://docs.qgis.org/3.16/en/docs/training_manual/forestry/stands_digitazing.html#basic-fa-digitize-the-forest-stands)  and [14.4.3](https://docs.qgis.org/3.16/en/docs/training_manual/forestry/updating_stands.html#basic-ty-digitizing-forest-stands-from-cir-imagery) are showing the old snapping options form and using map units as unit of measure. My Guess is that the form has to be changed and the units of measure would be meters.

Old Form 
![image](https://user-images.githubusercontent.com/45123660/149659298-899d785f-0dd2-4b69-bec4-a23014f3b633.png)

New Form 
![image](https://user-images.githubusercontent.com/45123660/149658426-afc0df1c-2e79-408e-8a0a-b113bb3ec39e.png)

**Comment by DelazJ** [comment]
@eboelcke Can you provide URL in your reports, please? Much easier to track and fix the lessons you are referring to. Thanks

**Comment by eboelcke** [comment]
I certainly will do? Thanks for the advise. Sent from Mail for Windows From: Harrissou Sant-annaSent: Sunday, January 16, 2022 10:03 AMTo: qgis/QGIS-DocumentationCc: eboelcke; MentionSubject: Re: [qgis/QGIS-Documentation] QGIS Training Manual - Project Snapping Options (Issue ***@***.*** Can you provide URL in your reports, please? Much easier to track and fix the lessons you are referring to. Thanks—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by tlh22** [comment]
Hi @DelazJ. I have started on this issue - again because it seemed simple. If there is any priority for issues, let me know and I will look at them next.

I have a couple of queries about substitutions; 
a. I want to include the topologicalEditing icon (mIconTopologicalEditing). It exists in the substitutions.txt file. I have run the scripts/find_set_subst.py script., however, when I make the html, it is not picked up. Am I missing something? 
b. I want to add "Follow Advanced Configuration" as shown in the image below. (I don't think overlaps should be allowed for the digitising). I couldn't find an icon that was the same, however, it looks like they are using mActionAvoidIntersectionsLayers. Is this correct? What would be the best way to confirm this?

![image](https://user-images.githubusercontent.com/11859865/186517812-c873bc60-9ba2-46d0-bf15-744835951e14.png)

Many thanks

**Comment by DelazJ** [comment]
> a. I want to include the topologicalEditing icon (mIconTopologicalEditing). It exists in the substitutions.txt file. I have run the scripts/find_set_subst.py script., however, when I make the html, it is not picked up. Am I missing something?

Hmmm, no! It should work but hard to say without a branch to review. Stupid question but did you surround it with the `|`? No typo? Otherwise, you can manually copy the substitution reference and paste it in the substitutions list at the end of the file....
>b. I want to add "Follow Advanced Configuration" as shown in the image below. (I don't think overlaps should be allowed for the digitising). I couldn't find an icon that was the same, however, it looks like they are using mActionAvoidIntersectionsLayers. Is this correct? What would be the best way to confirm this?

I'm afraid I do not get all the points (sorry) but you might find digitizing icons used in the docs referenced at https://docs.qgis.org/testing/en/docs/documentation_guidelines/substitutions.html#digitizing-and-advanced-digitizing and at https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#overlapping-control (in play). And I think you assumed right.

**Comment by DelazJ** [comment]
About the issue itself, as exposed by @eboelcke in the first message, I just want to stress that IMHO the training manual is not the place to explain the options or how they play together. The user manual intends to do that, and the abovementioned user manual link might cover these considerations (if not, let's clarify there). The training manual should instead provide scenarios in which some of these tools are used in order to obtain a particular result.
