### ISSUE TITLE
QGIS 3.22 Field Calculator Chapter 14.5.2 

### ISSUE THREAD

**Issue by eboelcke** [qgis/QGIS-Documentation#7289]
Apparently the Field Calculator has been changed and it doesn't show any longer the Record tab, showing instead a Record and  Attributes option where the $rownum does not shows any more. This variable is not shown neither at any of the other options and, when using the more likely possibility "@row_num" variable it produces unexpected results. The id numbers do not relate to the ids  of the stands but to some other relation. i.e the first row with an id of 17 as an @row_number of 111
old Field Calculator
![image](https://user-images.githubusercontent.com/45123660/149811840-15ee2e9f-b73c-4256-baae-9cf29ae4f3db.png)
new Field Calculator
![image](https://user-images.githubusercontent.com/45123660/149812131-d3a868bb-0938-4f05-b6a7-bba4fbb1cc76.png)

Page URL: https://docs.qgis.org/3.16/en/docs/training_manual/forestry/systematic_sampling.html

**Comment by DelazJ** [comment]
>  i.e the first row with an id of 17 as an @row_number of 111 old Field Calculator

I only quickly read the lesson but I don't think this is an issue. A populated field called id can't necessarily match with the row_number, particularly if you have deleted features from the layer: row_number updates but id doesn't. Also depends on whether the grid creation tool follows the same order as in the old version. 
To update the docs, we should care about keeping the spirit, the notions but not worry about 100% match with old docs.

**Comment by eboelcke** [comment]
@DelazJ As far as I can understand, the authors are trying to set an enumeration system more sensible for the survey ahead. Quote:

> Nevertheless, the number values in the id field are not so good. It would be better if the naming would be something like p_1, p_2.... You can create a new column for the systematic_plots_clip layer:
And direct the user to apply the field calculator on the systematic_ sequence like (p_1, p_2, ..........p_n) that would be use to label the survey points.

Since the variable $rownum has been removed I couldn't figure out how to replace it. When using the variable @row_number on systematic_plots_clip.shp it produces an unexpected - and rather amazing - result. ie The first point with and original id of 17 as result of the "Regular Points" tool, has a row_column value of 18 - that makes sense since id start at 0 while row_column at 1 - All the points on this table equal id + 1. 
When applying the "clip"  tool to the systematic_plots.shp the resulting layer not only does not keep the original id sorting but the row numbers as applied by @row_number seem to be at random. That exceeds me, perhaps the behavior may be the expected or perhaps ith might be a clip tool bug.

![image](https://user-images.githubusercontent.com/45123660/151164181-4faf6674-ac0b-488f-8084-5a06ce43d3e4.png)

Page URL: https://docs.qgis.org/3.16/en/docs/training_manual/forestry/systematic_sampling.html

**Comment by nkleinbaer** [comment]
@eboelcke the intent of the tutorial is just to build a text field  (`Plot_id`) with formatted strings that follow the North/South + East/West pattern generated by the regular points tool (which is already stored as an integer in the `id` field). They instruct you to use the following expression to do so:
```
concat('P_', $rownum )
```
 `$rownum` is now called `$row_num`, but the bigger problem is that row_num doesn't always match the value in the `id` field (particularly after using clip, as you noted). I guess the way the docs are written there is an assumption that they would match, but there is no reason you can't use that `id` field in the expression directly:
```
concat('P_', to_string("id"))
```

**Comment by nkleinbaer** [comment]
Ahh, I think I see what you are saying ....

Following the existing directions exactly (but substituting `@row_number` for `$rownum`), I see the problem you describe -- ordering is completely messed up:
![example1](https://user-images.githubusercontent.com/47011214/153721478-918c2f4e-c2d2-4a55-929c-15ea3951a66e.png)

Labeling based on `id` field instead, as I mentioned above, gives a more orderly result:
![example2](https://user-images.githubusercontent.com/47011214/153721481-6f80d505-b89f-4ec3-b941-787a4ce09c22.png)

Nonetheless, the plot ids do not start from "P_1" as is shown in the tutorial (I was not considering this before). I found, however, that I could replicate the labeling scheme shown in the tutorial by using the `Clip vector by mask layer`  tool (rather than the 'normal' `vector>geoprocessing>clip` tool) and creating labels based of `@row_number` 
![example3](https://user-images.githubusercontent.com/47011214/153721401-2493903c-9b18-40f3-8dce-d2ac1bb5caac.png)


The reason is that the 'normal' clip tool uses the `native:clip` algorithm, whereas the `Clip vector by mask` tool uses the `gdal:clipvectorbypolygon` algorithm.  As @DelazJ mentions, the row number is automatically updated when features are deleted, so of course it will not match the `id` field (which is not updated) . The `gdal:clipvectorbypolygon` algorithm, however, at least maintains the original _ordering_ of the rows, whereas  `native:clip` does not. 

I don't think this could really be considered a "bug" in `native:clip` ... I do not see anything in the docs that would indicate maintaining the row ordering is expected behavior, and it is really only causing an issue in this specific use case ... but it would at least agree with this :
>This is particularly confusing for somebody using the manual, like myself,

IMO it would be worth updating the instructions in the docs so that folks following along step by step do not run into the same confusion.
