### ISSUE TITLE
PDF files of the User Guide / Manual for 3.22 version and "testing" version are not valid / broken

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Documentation#7379]
## Description

See
- https://docs.qgis.org/3.22/pdf/en/ and https://docs.qgis.org/3.22/pdf/en/QGIS-testing-DesktopUserGuide-en.pdf
- https://docs.qgis.org/testing/pdf/en/ and https://docs.qgis.org/testing/pdf/en/QGIS-testing-DesktopUserGuide-en.pdf

The User Guide / Manual PDF files have usually a size of about 40 MB, while those PDF files for 3.22 and "testing" have a size of 1 MB.

Furthermore, those PDF files for QGIS 3.22 are incorrectly named QGIS-testing-*.pdf instead of QGIS-3.22-*.pdf.

https://lists.osgeo.org/pipermail/qgis-user/2022-March/050934.html

**Comment by agiudiceandrea** [comment]
@DelazJ thanks! The PDF files of the Desktop User Guide for the "testing" and the 3.22 versions are fixed now.

Anyway, the 3.22 folder at https://docs.qgis.org/3.22/pdf/en/ contains the old incorrectly named QGIS-testing-\*.pdf files besides the new correctly named QGIS-3.22-\*.pdf files.

**Comment by DelazJ** [comment]
> Anyway, the 3.22 folder at https://docs.qgis.org/3.22/pdf/en/ contains the old incorrectly named QGIS-testing-*.pdf files besides the new correctly named QGIS-3.22-*.pdf files.

@rduivenvoorde Can you take care of this please? I can't find where the files are stored. Thanks.

**Comment by rduivenvoorde** [comment]
Pff, that's because If peeps start doing things half instead of in 1x all, it get's messy. IF we want all after a new release/LTR everything in place, then let's plan that. Not like now that some scripts are fixed, others not etc etc...
For what I know @DelazJ and I have upcoming friday or saturday planned to recreate the builds...  If we want this earlier (it's still a release candidate isn't it?) then we should plan it. Not react on everything.
I've removed the testing ones
