### ISSUE TITLE
Merge pull request #2678 from m-kuhn/transaction-group

### ISSUE THREAD

**Issue by qgis-feature-tracker** [qgis/QGIS-Documentation#758]
Original commit: https://github.com/qgis/QGIS/commit/e1adc6379f7597c0aa4e53d50b70df36da080cca by m-kuhn

[FEATURE] Autotransaction mode and transaction groups

**Comment by SrNetoChan** [comment]
@m-kuhn Do you think this must be adressed somewhere in the Documentation? If so, where?

**Comment by m-kuhn** [comment]
It's a concept of editing. When this mode is turned on, all (postgres) layers from the same database are synchronised in their edit state: when one layer is put into edit state, all are, when one layer is committed or one layer is rolled back, so are the others. Also, instead of buffering edit changes locally, they are directly sent to a transaction in the database which gets committed when the user clicks save layer.

This is still an experimental feature, likely to be place on project level instead of application level.

So to answer your question, yes, I think it should be put in the documentation but tagged as "experimental".

**Comment by SrNetoChan** [comment]
So, If I understand well, this is not available from qgis gui (at least now). Should I tag this for PyQGIS Cookbook instead?

**Comment by m-kuhn** [comment]
It is. In settings -> options -> data sources -> create transaction groups automatically

**Comment by SrNetoChan** [comment]
Got it! thanks!

**Comment by DelazJ** [comment]
@m-kuhn wrote:
>It's a concept of editing. When this mode is turned on, all (postgres) layers from the same database are synchronised in their edit state: when one layer is put into edit state, all are, when one layer is committed or one layer is rolled back, so are the others. 

You mean all layers from the database or all linked ones (especially in case of relations)?

**Comment by m-kuhn** [comment]
The reason for the implementation was relations, but in its incarnation it affects all layers from the database. I think switching only the related ones would not have been very transparent to the user and I actually like that I have to do less clicks this way.

**Comment by m-kuhn** [comment]
This was moved from app settings to project properties for 2.16. Is this worth mentioning in the 2.14 documentation already? Or should there be an issue that it needs updating for 2.16?

**Comment by DelazJ** [comment]
I would say, there should be an issue report to have it moved to project properties for 2.16.

We should keep the doc consistent with the release it belongs to and given that this option is available in 2.14, user might need to know how it works. Then if in 2.16, he finds it in another part, no problem, he has keys to understand its functionalities.
