### ISSUE TITLE
Map legend has no reference to Filter legend by expression and by map

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS-Documentation#767]
In the users manual, Introduction, QGIS GUI, the Map Legend chapter makes no reference to the Filter Legend by Expression, and Filter Legend by map. Not sure if this is somewhere else. Should we include it?

http://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_gui.html#map-legend

**Comment by SrNetoChan** [comment]
Screenshot have been updated here #770

**Comment by DelazJ** [comment]
can someone plz let me know how "filter legend by expression" works, how can it be used? I'm unable to figure out. Thanks.
@mhugo ?

**Comment by mhugo** [comment]
@DelazJ This is probably better to see it in the composer.
If you have a legend on a layer that has different legend items (from a rule-based symbology for example), you can specify a boolean expression to filter which of the legend items of this layer will be displayed

**Comment by DelazJ** [comment]
@mhugo Thanks for the reply
For the print composer legend, I'd cheked and understood easily the behaviour. But I don't know why, as for the map extent tool, I was expecting that it filters all the layers in the panel. Maybe because of the name ("Filter legend by expression" and not "Filter layer legend by expression" or something that lets understand it applies only on a single layer)

Let's stay in the layer panel. So it just hides the style from the layer panel but doesn't hide the corresponding features (I used a quick categorized style) in the map canvas. Is it the intended behaviour : Have features visible in the canvas but with no information in the tree (and legend)?
And to be sure to have a style "removed" from the tree, the expression should return:
- a value that matches at least one of the style category value
- or all the features of the style should return false ?

Another point (sorry!) that may be worth an issue report (let me know if I should file a ticket) is that (in 2.14), if I have a categorized style, then i filter one by expression and then uncheck manually the another style, It is just removed from the tree instead of being unchecked. You can end up with a layer with no style in the tree but features shown in canvas. The unchecked category should remain in the tree, no? I need to clear the expression or open layer properties before retrieving the lost category.
Thanks again

**Comment by mhugo** [comment]
@DelazJ I agree ""Filter layer legend by expression" would be a better name.

> Is it the intended behaviour : Have features visible in the canvas but with no information in the tree (and legend)?

Yes, the intention is to act on the legend, not on the mapcanvas

And to be sure to have a style "removed" from the tree, **all the features of the style should return false**

About the issue, is it related to that : ?
http://hub.qgis.org/issues/13959
https://github.com/qgis/QGIS/pull/2557

**Comment by DelazJ** [comment]
@mhugo wrote:
> Yes, the intention is to act on the legend, not on the mapcanvas

> And to be sure to have a style "removed" from the tree, all the features of the style should return false

Ok. Then result is coherent. Can you give me a case where someone may want to hide the item only in the legend tree, so that the doc points readers to an use case of this feature? Thanks.
> About the issue, is it related to that : ?
http://hub.qgis.org/issues/13959
qgis/QGIS#2557

That is it. I read that report weeks ago but doesn't link it to this feature. I'd have rechecked.

**Comment by mhugo** [comment]
> Can you give me a case where someone may want to hide the item only in the legend tree, so that the doc points readers to an use case of this feature?

There may be simpler use cases, but the initial need was linked to a "mask" were the user wants to highlight only a part (= a polygon selection) of the map, and thus hide the rest. In that case legend items of features that are hidden by the mask should not appear. The "mask" plugin on the qgis repository provides a new expression function "in_mask" that allows to filter legend items outside of the current mask polygon.
