### ISSUE TITLE
Depevolepers guide: "Who manages the PR queue" (?)

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Documentation#8000]
## Description

In the "Development Process" chapter of the Depevolepers guide it is stated that:

> If you feel the PR is not receiving the attention it deserves your options to accelerate it should be (in order of priority):
> ...
> Send a message to Marco Hugentobler (who manages the PR queue).

If it is still valid, then we need to add the e-mail address of Marco Hugentobler, otherwise we need to update or remove the line.

Page URL: https://docs.qgis.org/testing/en/docs/developers_guide/git.html#submitting-pull-requests

**Comment by DelazJ** [comment]
@agiudiceandrea I'm afraid it is not valid. AFAIK (and at least since we moved to github) nobody is officially in charge of PR queue and Marco is no more that active in the project. There has been a discussion regarding PR queues and I think Nyall and Matthias were named somewhere but I can't recall for what, and to what extent.
I'd suggest removal of that row in the meantime.
