### ISSUE TITLE
Broken version of docutils doesn't render lists correctly

### ISSUE THREAD

**Issue by esnyder-rve** [qgis/QGIS-Documentation#8024]
I'm working on a new layout for processing algorithms, and noticed a bug in docutils. Unordered lists weren't receiving bullets and were being styled with `list-style: none;`.

Issue:
![Screenshot 2023-02-03 082608](https://user-images.githubusercontent.com/61027950/216614744-f9604e2f-757e-47b4-a508-0e0710c3c88c.png)

Resolved:
![74986b2c-18ff-41ce-b2d8-b29888aa47f4](https://user-images.githubusercontent.com/61027950/216614794-25ed198d-1fd9-45f3-88cd-9c9e6425dac9.jpg)

The solution to this problem is reverting docutils to a previous version by explicitly adding `docutils` and the version to the REQUIREMENTS.txt file like:

    docutils==0.6

**Comment by SrNetoChan** [comment]
I have confirmed this building it locally, but it seems to still be working correctly on the website. Maybe It differences in the building platform? @rduivenvoorde Do you know if we still use 20.04?

![image](https://user-images.githubusercontent.com/3607161/216784913-07a8aca1-659d-4773-b7a5-14fb046e4f5b.png)

@esnyder-rve why docutils 0.6? it's from 2009. The newest version is from 0.19.

**Comment by DelazJ** [comment]
Hi
This issue happens only if you (re)`pip install -r REQUIREMENTS.txt` your environment in the venv file so will affect newcomers but shouldn't affect our server whose environment is not rebuilt every time afaik. The versions there are not the latest ones.
There have been some issues with recent versions of docutils/sphinx/rtd and I think things are getting stable now. Regarding the suggestion to move back to docutils 0.16, note that rtd theme at 1.2.0rc3 already fixes the issue you pointed (though still remains an issue with the bottom left menu, but that is also fixed in their master). The stable release should be out soon.
So I'm personally more incline to wait a few weeks and have things sorted magically and run the most recent versions of all.

**Comment by esnyder-rve** [comment]
I guess I miss-read some of the various version numbers being thrown around in these sources:

https://stackoverflow.com/questions/67542699/readthedocs-sphinx-not-rendering-bullet-list-from-rst-file

https://github.com/readthedocs/sphinx_rtd_theme/issues/1115

It *seems* to be an issue with `docutils>=0.17`

**Comment by esnyder-rve** [comment]
@DelazJ Do we know what version of `docutils` the server is using?

**Comment by DelazJ** [comment]
@esnyder-rve As far I understand the docker image behind the docs build uses https://github.com/qgis/QGIS-Website/blob/master/REQUIREMENTS.txt

**Comment by esnyder-rve** [comment]
Ok, so `docutils` is not explicitly specified, and will be using the highest compatible version for the stated dependencies. I will check and see what actual version is being pulled.

**Comment by esnyder-rve** [comment]
@DelazJ The version that gets requested for the QGIS-Website `REQUIREMENTS.txt` is `docutils<0.18;>=0.14` and version `0.16` is what gets installed. `0.16` is before the issue. So, we could either change the requirements file in this repo to match the QGIS-Website version (which will automagically pull a valid `docutils`, or we could explicitly set `docutils` to version `0.16`.

**Comment by rduivenvoorde** [comment]
Feel free to explicitly set a version in the requirements.txt, but as Harrissou tells: it is the requirements.txt of the Website master branch which is actually used for the building of the Docker images, NOT the one which is in the docs repo
