### ISSUE TITLE
QGIS Tutorial 6.2.4 

### ISSUE THREAD

**Issue by desertjimmymax** [qgis/QGIS-Documentation#8103]
## Description
Should this line in 6.2.4 ""highway" NOT IN ('footway', 'path', 'unclassified', 'track') AND "highway" IS NOT NULL" instead read ""highway" NOT IN ('footway', 'path', 'unclassified', 'track') OR "highway" IS NOT NULL?

Page URL:

**Comment by DelazJ** [comment]
@desertjimmymax I think `"highway" NOT IN ('footway', 'path', 'unclassified', 'track') AND "highway" IS NOT NULL"` is the correct syntax here. We want to select features that are not of footway, path, ... types  but have a value filled. 
Using `OR "highway" IS NOT NULL` in the expression you reintroduce the footway, path,... roads types because they are not null.
Not sure if my explanation is clear but if you run the expressions in QGIS, you'll notice the difference in the number of returned features. And then check in which case you actually exclude the types we do not want.
Closing as not a docs issue.

PS: please fill the page URL when reporting an issue, it makes it easier for us to find what it is about. Thanks.
