### ISSUE TITLE
Doc Qgis server : Big typo

### ISSUE THREAD

**Issue by image80** [qgis/QGIS-Documentation#8134]
The typo is described here : https://lists.osgeo.org/pipermail/qgis-user/2023-March/052763.html

**Comment by DelazJ** [comment]
@image80 Can you please explain what the typo actually is? The only URL referencing the docs I can see there is https://docs.qgis.org/3.28/en/docs/training_manual/qgis_server/wms.html#getmap-requests and I don't see the URLs you are using in your request there. I guess you were somehow following the training manual (or server install?), but please take more time to provide a more detail report to help us fix the issue. thanks

**Comment by agiudiceandrea** [comment]
@DelazJ, the issue is in the QGIS Server Manual at https://docs.qgis.org/testing/en/docs/server_manual/getting_started.html#serve-a-project
The Server Manual gives instructions on how to install and configure the Apache HTTP server, in which case the server URL is set to http://qgis.demo/cgi-bin/qgis_mapserv.fcgi, and how to install and configure the NGINX HTTP server, in which case the server URL is set to http://qgis.demo/qgisserver instead.

Later in the text, at https://docs.qgis.org/testing/en/docs/server_manual/getting_started.html#serve-a-project, the following URL is given as an example to test the server:
```
http://qgis.demo/qgisserver?MAP=/home/qgis/projects/world.qgs&LAYERS=countries&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&CRS=EPSG:4326&WIDTH=400&HEIGHT=200&BBOX=-90,-180,90,180
```

Clearly, that URL is only valid if the user followed the instructions to install and configure the NGINX HTTP server, while it is not valid if the user followed the instructions to install and configure the Apache HTTP server. Anyway, this info is not specified in the text, so a user that followed the instructions to install and configure the Apache HTTP server will not understand why the server do not correctly respond to the request.

I think that possible fixes are:
1. just specify that such URL is valid for the NGINX HTTP server configuration
or
2. specify that such URL is valid for the NGINX HTTP server configuration and add the correct URL also for the Apache HTTP server configuration (`http://SERVER/cgi-bin/qgis_mapserv.fcgi?MAP=/home/qgis/projects/world.qgs&LAYERS=countries&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&CRS=EPSG:4326&WIDTH=400&HEIGHT=200&BBOX=-90,-180,90,180`)
or
3. change the the NGINX HTTP server configuration instructions in order to use the same server URL as in the Apache HTTP server configuration

**Comment by DelazJ** [comment]
Thanks @agiudiceandrea for your helpful and clear input.
Option 3 (or going the opposite way from the apache instructions as most of the services examples use the nginx syntax) might be the best option but it requires more work and skills so going for now with option 2.
