### ISSUE TITLE
QUICK OSM ISSUES

### ISSUE THREAD

**Issue by birsu11** [qgis/QGIS-Documentation#8525]
## Description

 Error in the QGIS log window, then the QuickOSM panel, copy/paste it and please report it, if you know how to copy/paste QGIS logs. Please check pinned tickets first.
Page URL:

**Comment by DelazJ** [comment]
Hi @birsu11 ,
This repository is dedicated to [documenting QGIS](https://docs.qgis.org),  and the issue you are reporting does not seem related at all.
It is unclear to me what it is about but issues with QuickOSM should be reported in their bug tracker: https://github.com/3liz/QuickOSM and of course, check if your problem is not already reported.
I'm closing your report. Thanks for understanding.
