### ISSUE TITLE
Training Manual - 3.2.5 (Scale Dependent Visibility)

### ISSUE THREAD

**Issue by WA-Spatial** [qgis/QGIS-Documentation#867]
In the scale dependent visibility section where setting the scale factors one of the key points states:
**- Change maximum to 1:10,000** - This should be** Change minimum to 1:10,000**. The screen shot of this does show that the minimum was changed to 1:10,000 and is correct.

**Comment by yjacolin** [comment]
Any link to the training manual to help us to find the incorrect sentence faster? Thanks.

**Comment by DelazJ** [comment]
@WA-Spatial  this has been fixed in master and be available with the next doc release (http://docs.qgis.org/testing/en/docs/training_manual/basic_map/symbology.html). I also fix it in 2.8 doc (https://github.com/qgis/QGIS-Documentation/commit/cf60cdc20ee15847bd97af13b6e64d0540555201) but not sure it's worth.
