### ISSUE TITLE
QgsLayout.setRect() call missing from cookbook example?

### ISSUE THREAD

**Issue by RaineEkman** [qgis/QGIS-Documentation#8897]
## Add setRect() to the Map Rendering and Printing section?

I helped out in debugging a PyQGIS script, where the PDF export was implemented more or less straight from the PyQGIS cookbook. The problem was a missing call to layout.setRect(), which I found out through [Erich Purpur's blog](https://library.virginia.edu/data/articles//how-to-create-and-export-print-layouts-in-python-for-qgis-3):

> So in the previous code I created a map, which is a QgsLayoutItemMap object. My apologies but the map.setRect() method confuses me and to be honest, I can't explain what it does or why its there. But it is necessary for the map to exist. The arguments (20, 20, 20, 20) seem to have no effect on the map but without calling this method, you'll get an error. 

Now, I could've just added the missing line in a PR, but I think it'd be better with at least some explanation on what goes on. This is the code example I'm suggesting:

```
project = QgsProject.instance()
layout = QgsPrintLayout(project)
layout.setRect(20,20,20,20) # The necessary mysterious line
layout.initializeDefaults()
```

Page URL: https://docs.qgis.org/3.28/en/docs/pyqgis_developer_cookbook/composer.html

**Comment by DelazJ** [comment]
Hi @RaineEkman 
Thanks for reporting. I confirm that without `map.setRect()`, the code provided in the blog post does not display the map at the target extent. I have the layout map spinning forever. I can't say what that `setRect()` method refers to, as I can't find it in these classes docs (just [here](https://qgis.org/pyqgis/master/gui/QgsMapCanvasItem.html#qgis.gui.QgsMapCanvasItem.setRect)). However, I think the issue comes from the use of `map.setExtent()` instead of `map.zoomToExtent()` ([docs](https://qgis.org/pyqgis/master/core/QgsLayoutItemMap.html)), used in the docs sample. The docs example still works nicely here on 3.34.3.
