### ISSUE TITLE
Add language switcher button to docs.qgis.org

### ISSUE THREAD

**Issue by jidanni** [qgis/QGIS-Documentation#9149]
The user has just landed on e.g.,
https://docs.qgis.org/3.34/ru/docs/user_manual/processing_algs/gdal/vectorgeoprocessing.html
How did the user land there? Google sent the user there.
The document looks interesting. Alas, it is not in the user's native language.
However no matter how hard the user looks, the user cannot find the language switcher button.

The only hope left is for the user to manually substitute the "ru" in the URL for "en", and give it a try.
https://docs.qgis.org/3.34/en/docs/user_manual/processing_algs/gdal/vectorgeoprocessing.html
The gamble pays off and the user can now proceed to read in their native language.

Therefore please add a language switcher button.

P.S., maybe also don't let Google etc. cache e.g., "3.34" specific versions, always giving it a canonical URL.

**Comment by DelazJ** [comment]
> However no matter how hard the user looks, the user cannot find the language switcher button.

@jidanni Obviously, I wouldn't call that a "hard" search. Otherwise the user would have seen, depending on their device, in the accordion menu or the bottom left drop-down button, a list of supported languages and versions. 
![Screenshot_20240703-043109_DuckDuckGo](https://github.com/qgis/QGIS-Documentation/assets/7983394/a0ec4ba3-0a21-470f-a32f-9cf4defc73e8)
There is nothing else we could do here.
