### ISSUE TITLE
Get involved link is badly configured

### ISSUE THREAD

**Issue by ponceta** [qgis/QGIS-Documentation#9234]
## Description

- [x] On every documentation page, the status of the translation is shown

![image](https://github.com/user-attachments/assets/202ff47f-8b7c-4245-8da2-80ff5e437bb2)

- [ ] The link to get involved into the translation points to :

https://qgis.org/#becoming-a-translator
instead of 
https://qgis.org/community/involve/#translate-qgis

Page URL: ALL

**Comment by DelazJ** [comment]
Well the issue is a bit bigger... The new page is only a redirection to how to technically translate in the docs guidelines; the instructions on how to effectively join on Transifex have been deleted during the migration. I am resurrecting them in #9236 and we should consider skipping the website get involved page you are suggesting and redirecting directly to the docs instructions.
