### ISSUE TITLE
GDAL "Rasterize (overwrite *)" algs help pages: not properly opened clicking the processing's Help button in Desktop

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Documentation#9479]
## Description

Clicking the Help button of the "Rasterize (overwrite with attribute)" (`gdal:rasterize_over`) and the "Rasterize (overwrite with fixed value)" (`gdal:rasterize_over_fixed_value`) processing algorithm's dialog window in QGIS Desktop, the pages at https://docs.qgis.org/3.34/en/docs/user_manual/processing_algs/gdal/vectorconversion.html#gdalrasterize_over and https://docs.qgis.org/3.34/en/docs/user_manual/processing_algs/gdal/vectorconversion.html#gdalrasterize_over_fixed_value will be opened. Anyway the pages are not displayed at the correct internal section corresponding to the algorithm.
The issue doesn't occur for "Rasterize (vector to raster)" and "Convert format" GDAL algorithms in the same "Vector conversion" group.

The issue occurs using both Google Chrome 131.0.6778.140 and Mozilla Firefox 133.0.3 on Windows 10.

Page URL:

**Comment by DelazJ** [comment]
Hi @agiudiceandrea 
Thanks for catching up.
From a quick glance, this is due to the "_" character in the algs id (`gdal:rasterize_over`), hence in their anchor (`gdalrasterize_over`). When there is an underscore in an anchor, Sphinx, presumabily, generates a URL where this is replaced with "-". So the generated link in the docs are https://docs.qgis.org/3.34/en/docs/user_manual/processing_algs/gdal/vectorconversion.html#gdalrasterize-over and https://docs.qgis.org/3.34/en/docs/user_manual/processing_algs/gdal/vectorconversion.html#gdalrasterize-over-fixed-value while QGIS would always look for a URL with underscore.
To have the correct link displayed, and because I'm not sure we can redirect in docs, a proper fix would be IMHO to alias these algs to an id without underscore (`rasterizeover` and `rasterizeoverfixedvalue`) in QGIS itself. I don't have QGIS around but browsing the docs, we usually don't use such characters in algs id, only letters. So they'd be aligned with the others and we could set this (only [a-z] characters) up as a rule for algs id.

**Comment by DelazJ** [comment]
Another solution, maybe cleaner, because transparent to users, is to tweak the function that creates the URL in QGIS to replace any "_" in the id by "-". Assuming this is not exposed in Python.
